### ISSUE TITLE
Some Prop Morphs Don't Export To UE4

### ISSUE THREAD

**Issue by iamthemulti** [daz3d/DazToRuntime#1]
Some prop morphs are available in the morph selection dialog, but do not export properly to Unreal Engine 4. This was found using a geograft that parents itself under the character. The geograft prop itself exports properly, only morphs are unavailable.

**Comment by jjanzer** [comment]
Thanks, to help speed up the dev effort for a fix, can you let us know which assets you're working with so we can reproduce and look at it?
