### ISSUE TITLE
Importing genesis 8 into UE5 skeleton issue

### ISSUE THREAD

**Issue by arronhuk** [daz3d/DazToRuntime#22]
I installed the beta build of the plugin into UE5 and manged to import a model with the viking handmaiden clothing set but I am getting a lot of error about missing bones saying I have to re-save the skeleton. I have 'saved all' but the issue keeps coming up and I cannot open the content browser as the error closes the content browser when the alert pops up (this is a failing in UE5 using temporarily open windows not the plugin) but is there a way of sorting the skeletons? do I have to open each clothing item and re-align the mesh to the UE skeleton?

Thanks
Arron

**Comment by Popinjayishuman** [comment]
Currently The Ue5 bridge is not fully supported but we are looking into full integration with the release coming next year. We will take a note of this while solving issues for the next update. In the meantime you could check out the discord server here: https://discord.gg/b6TRcszs
There may be some help from other users testing out the bridge!
