### ISSUE TITLE
Any animation distorts the whole mesh

### ISSUE THREAD

**Issue by ghost** [daz3d/DazToRuntime#25]
If I import any figure, let's say G8F dev load, and then send it to UE5, it looks ok. But if I apply any animation from DAZ, even the one that always comes with import and doesn't do any movements, even with this animation, the whole model become stretched, especially the head.
The same happens with G3F and with any other figure.

**Comment by TessGaming** [comment]
I got the model to come in just fine and retargeted to work with Mixamo after some trial and error. However now i have my own issue with animation - When i try to import animation from Daz it just... doesn't work. Like i made a simple wave animation and you can see slight movement in the shoulder but that is it. 
I attempted to retarget it to the basic skeleton and it's just again a basic shoulder movement. Not sure what im doing wrong :/

**Comment by samjay3d** [comment]
Sorry, you guys are hitting into an issue on the animation. Could you share more info. Which animation you are exporting? A screenshot of what you are seeing in Unreal? 

One thing I can say right off is the default animations don't work outside of Daz by default. You will need to convert the animate2 blocks to Daz Studio Key Frames. 

Just need to right-click the aniMate Timeline at the bottom and bake keyframes. 

![image](https://user-images.githubusercontent.com/71744685/126193056-49ea6b72-dc02-4573-a521-c580966e3cb7.png)

**Comment by TessGaming** [comment]
I got no errors uploading into Unreal. I got the animation to work by exporting it as an FBX And pulling it into unreal manually. Pain but not a big deal. I should also note - i do not use Animate2 i just use keyframes. It was a Very simple animation.

**Comment by ghost** [comment]
I didn't send any animation into UE5, but it still happens with the one that always appear when you send a character form DAZ to Unreal. Here it is:

![no_animation](https://user-images.githubusercontent.com/75087668/126877646-7e644ccd-c6fd-46ea-aa22-864c98fb3c58.jpg)
![default_animation](https://user-images.githubusercontent.com/75087668/126877645-24dd3248-ef6a-4bd8-9d4e-880845788eef.jpg)

The same happens with ANY animation. Even if I just add to keys in DAZ and move character's hand.
And with custom characters and mocap animations from DAZ everything is even worse. For example lips are distorted so hard that it looks like the character is very very angry. And the head shape is also distorted more than in the example above.
Here is the example:

![no_animation2](https://user-images.githubusercontent.com/75087668/126877997-669b2cfe-8d57-4070-9f4d-fb435bf0c81d.jpg)
![walk_animation](https://user-images.githubusercontent.com/75087668/126877998-fd1b8cf4-3b80-4117-9ca7-6d52f16d36c7.jpg)

Is this only me or you can get similar results? I mean, should we just wait for the fix or this is only me and I should search for what's wrong with my system and apps?
Thank you!

**Comment by ghost** [comment]
Hi! Could you please check if this is ok on your side with UE5?

**Comment by ghost** [comment]
Well, it was me :) I just selected the correct skeleton in Retarget tab and it fixed the issue
