### ISSUE TITLE
how to install this plugin for unreal 4.26 or 5 ?

### ISSUE THREAD

**Issue by polidox2** [daz3d/DazToRuntime#27]
I am using the official bridge from daz when i try compile my project i have this error:
PackagingResults: Error: Missing precompiled manifest for 'DazToUnrealRuntime'. This module was most likely not flagged for being included in a precompiled build - set 'PrecompileForTargets = PrecompileTargetsType.Any;' in DazToUnrealRuntime.build.cs to override.

i try download the version 5.0 i followed this wiki:
https://github.com/daz3d/DazToRuntime/blob/master/Unreal/DazStudioPlugin/README.md
last step i couldn't do it it says In VS2019 Change build output from "Current Document" up at the top to be "dzunrealbridge.dll".   there is no" change build output" in the top in visual studio 2019

 
please how to install this for 4.26 or 5 without any bug and problems? works smoothly with 4.25 and the official bridge from daz.

**Comment by polidox2** [comment]
it would be really nice to update the wiki with pictures.

**Comment by polidox2** [comment]
manage to found it. wiki not helpful though.

**Comment by dfarjoun** [comment]
How did you fix it? 
I'm using 4.26 and have the same problem.

**Comment by polidox2** [comment]
download the plugin of David here:
https://github.com/David-Vodhanel/DazToRuntime

it will fix it.
