### ISSUE TITLE
Cook failed how to fix that

### ISSUE THREAD

**Issue by polidox2** [daz3d/DazToRuntime#29]
https://imgur.com/a/H2Q0te6
I am having this error how to fix that ?

i use unreal 5 with the plugin who support unreal 5

**Comment by Popinjayishuman** [comment]
https://github.com/daz3d/DazToRuntime/releases/tag/4.2.0-unreal5EA

This is a link to a test version of ue5, feel free to give it a go. We will look into the error and see why it is happening however ue5 is not currently supported by the bridge.

**Comment by polidox2** [comment]
i fixed it , once i delete the folder "animation" it cook smoothly without problems.
