### ISSUE TITLE
4.27 support ?

### ISSUE THREAD

**Issue by polidox2** [daz3d/DazToRuntime#30]
Don't know why this plugin is not actively updated it's so important ;'(
hopefully we can get a support of 4.27 soon.

**Comment by Heavenskies11** [comment]
Same... we need an update! pls ^^

**Comment by Popinjayishuman** [comment]
We are currently working on support for 4.27 however in the meantime there is a link here that should work: 
https://github.com/David-Vodhanel/DazToRuntime/releases/tag/v4.2.0.41
