### ISSUE TITLE
JCM Morphs?

### ISSUE THREAD

**Issue by melMass** [daz3d/DazToRuntime#5]
Hi,

Does the bridge export JCM morphs? Or is it doing something to simulate them? 

Before heading into the source and trying to build it for mac I just want to make sure it does what I need, thanks for making it OpenSource!

**Comment by jjanzer** [comment]
You can export them in the morph export list, but they aren't controlled by the bridge at this time.

**Comment by melMass** [comment]
Thanks, I'm not a DAZ expert, but I know Unity quite well this is very trivial as long as I know how JCM morphs are setup. Do you know by anychance how they are setup in daz so that I can make a translation to Unity? Like is it only based on bones rotation?

I'll check the API to see if there is a way to query them and serialize them somehow

**Comment by jjanzer** [comment]
I don't recall if it's anything beyond pairing 2 bones and checking their axis rotations and then driving linearly the JCM from that. The Unreal bridge has support for this if you want to reference that as well.
